
[misc]
	#If unimplemented items should show that they are unobtainable in their item description
	"Show unobtainable description" = true
	#If Glow Squids should use our Glow Squid Renderer.
	"Replace Glow Squid Renderer" = true

