JEIEvents.hideItems(event => {
    event.hide([
        'additionalweapon:copper_axe',
        'additionalweapon:copper_battlestaff',
        'additionalweapon:copper_boots',
        'additionalweapon:copper_chestplate',
        'additionalweapon:copper_glaive',
        'additionalweapon:copper_greataxe',
        'additionalweapon:copper_greatsword',
        'additionalweapon:copper_halberd',
        'additionalweapon:copper_helmet',
        'additionalweapon:copper_hoe',
        'additionalweapon:copper_katana',
        'additionalweapon:copper_leggings',
        'additionalweapon:copper_pickaxe',
        'additionalweapon:copper_scimitar',
        'additionalweapon:copper_shovel',
        'additionalweapon:copper_spear',
        'additionalweapon:copper_sword',
    ]);
})