onEvent('jei.hide.items', event => {
    event.hide([
        'naturalist:venison',
        'naturalist:cooked_venison',
        'naturalist:antler',
        'naturalist:snail_shell',
        'naturalist:bear_fur',

        'naturalist:snail_bucket',

        'naturalist:bear_spawn_egg',
        'naturalist:bluejay_spawn_egg',
        'naturalist:boar_spawn_egg',
        'naturalist:butterfly_spawn_egg',
        'naturalist:canary_spawn_egg',
        'naturalist:cardinal_spawn_egg',
        'naturalist:caterpillar_spawn_egg',
        'naturalist:coral_snake_spawn_egg',
        'naturalist:deer_spawn_egg',
        'naturalist:elephant_spawn_egg',
        'naturalist:firefly_spawn_egg',
        'naturalist:giraffe_spawn_egg',
        'naturalist:hippo_spawn_egg',
        'naturalist:lion_spawn_egg',
        'naturalist:rattlesnake_spawn_egg',
        'naturalist:rhino_spawn_egg',
        'naturalist:robin_spawn_egg',
        'naturalist:snail_spawn_egg',
        'naturalist:snake_spawn_egg',
        'naturalist:vulture_spawn_egg',
        'naturalist:zebra_spawn_egg',
        'naturalist:_spawn_egg',
        'naturalist:_spawn_egg',
        'naturalist:_spawn_egg',
    ]);
});