onEvent('jei.hide.items', event => {
    event.hide([
        'orcz:goblin_2sword_spawn_egg',
        'orcz:goblinshield_spawn_egg',
        'orcz:orcsavage_2sword_spawn_egg',
        'orcz:orcshield_spawn_egg',
        'orcz:bigorcboss_spawn_egg',
        'orcz:orcsavage_2swordiron_spawn_egg',
        'orcz:orcshieldiron_spawn_egg',
        'orcz:orcsavageweird_spawn_egg',
        'orcz:squig_spawn_egg',
        'orcz:orcsavagemace_spawn_egg',
        'orcz:goblinsavagemace_spawn_egg',
        'orcz:orcsavagemaceiron_spawn_egg',
        'orcz:goblinwerid_spawn_egg',
        'orcz:goblinsavagebomb_spawn_egg',
        'orcz:spectre_squig_spawn_egg',
        'orcz:weirdboinecro_spawn_egg',
        'orcz:orcirongroupleader_spawn_egg',
        'orcz:orcsavagegroupleader_spawn_egg',
        'orcz:goblincammo_spawn_egg',
    ]);
})